export const cartActionTypes = {
    PUSH_TO_CART: '[CART] PUSH_TO_CART',
    POP_FROM_CARD: '[CART] POP_FROM_CART',
    INIT_TOTAL_PRICE: '[CART] INIT_TOTAL_PRICE',
    RESET_TOTAL_PRICE: '[CART] RESET_TOTAL_PRICE'
}
